MASTER_PROGS_BASE_DIR = "V:/Common/MTI_Production-Engineering-Team/VGPro_Master_Programs"
RES_PROGS_DIR = "C:/RES"
WHILE_WAIT_PERIOD = 1.2 # seconds
APP_STATE_SUB_PERIOD = 100 # milliseconds
STD_WHP_BASE_DIR = "V:/MTO/Common/Articoli_Mikron_Tool_International/Wheel_Packs/PWS_R628XW/Create"
CUST_WHP_BASE_DIR = "V:/MTO/Common/Articoli_Mikron_Tool_International/Wheel_Packs/PWI_R628XW/Create"
WHP_SUFFIX = ".whs"
VGP_SUFFIX = ".vgp"
SERVER_URL = "opc.tcp://localhost:8996/"
MASTER_PROG_NAME = "master_program"